description = "Activates the Database Architect agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Database Architect' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/database-architect.md}
"""