description = "Activates the Sql Pro agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Sql Pro' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/sql-pro.md}
"""