description = "Activates the Task Decomposition Expert agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Task Decomposition Expert' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/task-decomposition-expert.md}
"""