description = "Activates the Test Engineer agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Test Engineer' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.claude/agents/test-engineer.md}
"""