# Agent Configuration
# Configuration for all 7 specialized AI agents in the application pipeline
# Each agent uses Claude API with different models based on task complexity

# Job Matcher Agent - Evaluates job fit against search criteria
job_matcher_agent:
  model: claude-haiku-4-5-20251001  # Claude Haiku 4 for complex matching logic
  match_threshold: 0.70   # Minimum score to proceed (0.0-1.0)

  # Scoring weights for match calculation (must sum to 1.0)
  scoring_weights:
    must_have_present: 0.50        # Weight for must-have tech presence
    strong_preference_present: 0.30  # Weight for strong pref tech presence
    nice_to_have_present: 0.10      # Weight for nice-to-have tech presence
    location_match: 0.10            # Weight for location match

# Salary Validator Agent - Validates salary against expectations
salary_validator_agent:
  model: claude-haiku-4-5-20251001 # Claude Haiku for simple validation
  strict_validation: false  # Allow unclear salary if job otherwise matches

# CV Tailor Agent - Customizes CV for each job
cv_tailor_agent:
  model: claude-sonnet-4-5-20250929  # Claude Sonnet 4 for document generation
  template_path: current_cv_coverletter/Linus_McManamey_CV.docx
  output_dir: export_cv_cover_letter
  max_length_words: 800    # Maximum CV length in words

# Cover Letter Writer Agent - Generates personalized cover letters
cover_letter_agent:
  model: claude-sonnet-4-5-20250929   # Claude Sonnet 4 for document generation
  template_path: current_cv_coverletter/Linus_McManamey_CL.docx
  output_dir: export_cv_cover_letter
  max_length_words: 400    # Maximum cover letter length in words

# QA Agent - Validates generated documents and match scores
qa_agent:
  model: claude-haiku-4-5-20251001 # Claude Haiku for validation checks

  # Quality checks to perform
  quality_checks:
    - spelling_grammar       # Check for spelling and grammar errors
    - tone_professional      # Ensure professional tone
    - match_score_accurate   # Validate match score calculation
    - cv_cl_consistency      # Ensure CV and CL are consistent

  minimum_pass_score: 0.85  # Minimum QA score to proceed (0.0-1.0)

# Orchestrator Agent - Makes final application decisions
orchestrator_agent:
  model: claude-sonnet-4-5-20250929     # Claude Sonnet 4 for decision-making
  decision_policy: conservative  # Options: conservative, aggressive
  approval_mode: false        # Set true to require human approval

# Form Handler Agent - Automates web form submissions
form_handler_agent:
  model: claude-sonnet-4-5-20250929 # Claude Sonnet 4 for form automation
  timeout_seconds: 120    # Maximum time for form submission
  retry_attempts: 3       # Number of retry attempts on failure
