job_type: contract
duration: 6-12+ months
locations:
  primary: Remote (Australia-wide)
  acceptable: Hybrid with >70% remote
  exclude:
  - Full office-based
keywords:
  primary:
  - Data Engineer
  - Senior Data Engineer
  - Data Engineering
  secondary:
  - Analytics Engineer
  - Data Platform Engineer
  exclude:
  - Junior
  - Graduate
technologies:
  must_have:
  - Python
  - SQL
  - Cloud Platform (Azure/AWS/GCP)
  strong_preference:
  - PySpark
  - Azure Synapse
  - Databricks
  - Azure Data Factory
  - dbt
  nice_to_have:
  - Airflow
  - Kafka
  - Docker/Kubernetes
  - CI/CD
salary_expectations:
  minimum: 800
  target: 1000
  maximum: 1500
seek:
  enabled: true
  search_terms:
  - data engineer
  - data engineering
  location: Australia
  exclude_keywords: []
indeed:
  enabled: true
  search_terms:
  - data engineer
  - data engineering
  location: Australia
  exclude_keywords: []
